<?php
$conn = new mysqli("localhost","root","","campus_db");
$result = $conn->query("SELECT * FROM complaints ORDER BY complaint_id DESC");
?>

<!DOCTYPE html>
<html>
<head>
<title>Admin Dashboard</title>

<style>
body{
    font-family: 'Segoe UI';
    background:#f1f5f9;
    padding:20px;
}

/* TABLE */
table{
    width:100%;
    border-collapse:collapse;
    background:#fff;
    border-radius:10px;
    overflow:hidden;
    box-shadow:0 5px 15px rgba(0,0,0,0.1);
}

th{
    background:#0ea5a4;
    color:white;
    padding:12px;
}

td{
    padding:12px;
    border-bottom:1px solid #eee;
}

tr:hover{
    background:#f9fafb;
}

/* PRIORITY COLORS */
.low{color:green;font-weight:bold;}
.medium{color:orange;font-weight:bold;}
.high{color:red;font-weight:bold;}

/* BUTTONS */
button{
    padding:6px 12px;
    border:none;
    border-radius:6px;
    cursor:pointer;
    margin:2px;

}

.accept{
    background:#22c55e;
    color:white;
}

.reject{
    background:#ef4444;
    color:white;
}

/* IMAGE */
img{
    border-radius:6px;
}

/* POPUP */
.popup{
    position:fixed;
    top:20px;
    right:20px;
    background:#111;
    color:#fff;
    padding:10px 15px;
    border-radius:6px;
    display:none;
}
</style>
</head>

<body>

<h2>📋 Complaint Dashboard</h2>

<div id="popup" class="popup"></div>

<table>
<tr>
<th>Name</th>
<th>Priority</th>
<th>Problem</th>
<th>Location</th>
<th>Media</th>
<th>Action</th>
</tr>

<?php while($row = $result->fetch_assoc()) { ?>
<tr>
<td><?php echo $row['name']; ?></td>

<td class="<?php echo strtolower($row['priority']); ?>">
    <?php echo $row['priority']; ?>
</td>

<td><?php echo $row['description']; ?></td>
<td><?php echo $row['location']; ?></td>

<td>
<?php if($row['media']) { ?>
<img src="<?php echo $row['media']; ?>" width="80">
<?php } ?>
</td>

<td>
<button class="accept"
onclick="acceptComplaint(
'<?php echo $row['email']; ?>',
'<?php echo htmlspecialchars($row['name']); ?>',
'<?php echo htmlspecialchars($row['description']); ?>',
'<?php echo htmlspecialchars($row['location']); ?>',
'<?php echo htmlspecialchars($row['priority']); ?>'
)">
✔ Accept
</button>

<button class="reject"
onclick="deleteComplaint('<?php echo $row['complaint_id']; ?>', this)">
✖ Reject
</button>
</td>
</tr>
<?php } ?>

</table>

<script>
function showPopup(msg){
    let p = document.getElementById("popup");
    p.innerText = msg;
    p.style.display = "block";
    setTimeout(()=>{p.style.display="none";},2000);
}

// ACCEPT BUTTON
function acceptComplaint(name, priority, problem, location){

    let message = "📢 Campus Complaint Report\n\n" +
                  "👤 Name: " + name + "\n" +
                  "📍 Location: " + location + "\n" +
                  "⚠️ Priority: " + priority + "\n\n" +
                  "📝 Problem:\n" + problem + "\n\n" +
                  "-------------------------\n" +
                  "Generated by Campus System";

    navigator.clipboard.writeText(message)
    .then(() => {
        showPopup("Copied successfully!");
    })
    .catch(() => {
        alert(message); // fallback if clipboard fails
    });
}

// OPTIONAL: confirm before reject
document.querySelectorAll(".reject").forEach(btn=>{
    btn.addEventListener("click", function(e){
        if(!confirm("Are you sure to reject?")){
            e.preventDefault();
        }
    });
});

function deleteComplaint(id, btn){
    if(!confirm("Are you sure to reject?")) return;

    fetch("/campus-problem-reporter/backend/delete_complaint.php", {
        method: "POST",
        headers: {
            "Content-Type": "application/x-www-form-urlencoded"
        },
        body: "id=" + id
    })
    .then(res => res.text())
    .then(data => {

        console.log(data); // DEBUG

        if(data.includes("success")){
            let row = btn.closest("tr");

            row.style.transition = "0.3s";
            row.style.opacity = "0";

            setTimeout(()=> row.remove(), 300);

            showPopup("Complaint deleted successfully");
        } else {
            alert("Delete failed: " + data);
        }
    });
} 
</script>

</body>
</html> 